### ISSUE TITLE
Importing with --experimental-modules

### ISSUE THREAD

**Issue by tredondo** [janjakubnanista/downsample#1]
Thanks for the module! Is there a way to import a specific method in Node v8.5+ with the `--experimental-modules` flag? `import { LTTB } from 'downsample'` fails.

> SyntaxError: The requested module 'downsample' does not provide an export named 'LTTB'

**Comment by janjakubnanista** [comment]
@meteorpublish I will take a look at how the source code is transpiled into the resulting bundle, I guess that's where the issue lies. I only tested with node v9.1 so this went unnoticed

**Comment by meteorpublish** [comment]
Thanks. Same problem with Node v10.x.

**Comment by janjakubnanista** [comment]
The package build has been moved to `rollup` which should fix this issue and also make the package tree-shakeable
