### ISSUE TITLE
Support for ArrayBuffers

### ISSUE THREAD

**Issue by Christilut** [janjakubnanista/downsample#19]
Is it possible to support `ArrayBuffer` and similar structures like `Uint8Array`, `Float32Array`, etc?

Ideally it would be great if I can pass a `Uint8Array` as argument and it will give me the same type array back.

Right now I'd have to convert the ArrayBuffer to the DataPoint structure and that's very inefficient in my case.

**Comment by janjakubnanista** [comment]
Hey @Christilut ! Thanks for reaching out! I actually had a minute or two to draft the support for this, you can find the WIP PR in #20 

Please check it out, it's still very much WIP and all input is welcome!

**Comment by Christilut** [comment]
Wow that's fast! Awesome! 

I'd be happy to give it a test run and see what issues I find. Just let me know when it's ready for that :)
